---
title: "Longitudinal Ordinal Data (Logistic)"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{CLMM_logistic}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Generate longitudinal ordinal data, using logistic specification. 

This should be a marginal model - ordinal GEE should work. 

TODO: A simulation study to confirm recover of generating parameters. 

```{r CLMM1, eval = F}

library(MASS)
library(polycor)


 set.seed(6162021)

  out <- sim_dat_ord_logistic(N = 500,
                 number.groups = 2 ,
                 number.timepoints = 4,
                 reg.formula = formula( ~ Time + Group + Time*Group),
                 Beta = 0.5,
                 thresholds = c(0),
                 corr = 'ar1',
                 cor.value = 0.4)


  dat <- out$dat
  str(dat)

# Check the correlations:
polychor(x = dat$Y_comp[dat$Time == 'Time_1'], y = dat$Y_comp[dat$Time == 'Time_2'])
polychor(x = dat$Y_comp[dat$Time == 'Time_2'], y = dat$Y_comp[dat$Time == 'Time_3'])
polychor(x = dat$Y_comp[dat$Time == 'Time_3'], y = dat$Y_comp[dat$Time == 'Time_4'])


library(ordinal)
mod.clm <- clm(as.factor(Y_comp) ~ Group + Time + Group*Time, data= dat)
summary(mod.clm)
out$Beta
out$thresholds
library(emmeans)
emmeans::emmeans(mod.clm, pairwise ~ Group | Time)

st <- Sys.time()
mod.clmm <- clmm(as.factor(Y_comp) ~ Group + Time + Group*Time + (1|USUBJID),
                 data= dat)
et <- Sys.time()
et - st
summary(mod.clmm)
mod.clm$coefficients
mod.clmm$coefficients

mod.polr <- MASS:::polr(as.factor(Y_comp) ~ Group + Time + Group*Time ,
                        data= dat, method = 'logistic', Hess = T)
summary(mod.polr)
# same estimates, good!

# maybe not correct?
sigma2 <- ordinal::VarCorr(mod.clmm)
sigma2 <- as.numeric(as.data.frame(sigma2))
denom.logit <- sqrt( (sigma2 + (pi^2/3))/(pi^2/3) )

#------
# Generalized Estimating Equations:
library(multgee)
dat.gee <- dat
tmp <- order(dat.gee$id.geepack)
dat.gee <- dat.gee[tmp, ]
mod.gee <- ordLORgee(formula = Y_comp ~ Time + Group + Time*Group,
                     data = dat.gee,
                     id = id.geepack,
                     repeated = Time, LORstr = "uniform")
summary(mod.gee)
coef(mod.gee)

# library(geepack)
# dat.gee <- dat
# tmp <- order(dat.gee$id.geepack)
# dat.gee <- dat.gee[tmp, ]
# dat.gee$Y_comp <- dat.gee$Y_comp + 1
# mod.gee1 <- ordgee(ordered(Y_comp) ~ Time + Group + Time*Group,
#                    id = id.geepack,
#                    data = dat.gee,
#                    corstr = "exchangeable")
# summary(mod.gee1)

cbind('Gen_par' = c(out$thresholds, as.vector(out$Beta[-1,])),
      'CLM' = coef(mod.clm),
     # 'CLM_polr' = coef(mod.polr),
      'ord_GEE' = coef(mod.gee),
      'CLMM' = coef(mod.clmm),
      'CLMM_pop_avg_logit' = coef(mod.clmm)/denom.logit)

```
