---
title: "Vignette_13"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette_13}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Beta Distribution

TODO: Complete this. Find an R package with a Beta regression function. Provide a cleaner version of your custom estimation code. 


Review and run the code below to better understand the data distribution. 



### Generate cross sectional data


```{r Run1, eval = F}
library(SPR)
library(MASS)
library(polycor)

N = 1e5 #this should be divisible by however many groups you use!
number.groups <- 2
number.timepoints <- 1
#set.seed(2182021)



    dat <- data.frame(
                      'USUBJID' = rep(paste0('Subject_', formatC(1:N, width = 4, flag = '0')), length.out= N*number.timepoints),
                     # 'Group' = rep(paste0('Group_', 1:number.groups), length.out = N*number.timepoints),
                     'Group' = c(rep('Group_1', 0.75*N), rep('Group_2', 0.25*N)),
                      'Y_comp' = rep(NA, N*number.timepoints), 
                      #'Bio' = rep(rnorm(N, mean = 0, sd = 1), number.timepoints),
                      'Time' = rep(paste0('Time_', 1:number.timepoints), each = N),
                      stringsAsFactors=F)
    
        
        # Design Matrix
    X <- model.matrix( ~ Group , data = dat) 
    param <- matrix(0, nrow = ncol(X), dimnames=list(colnames(X), 'param'))
    param[] <- c(3, 7)

    
    # Parameters:
    mu <- X %*% param
    dat$XB <- as.vector(mu)
    dat$Y <- rbeta(n = N, shape1 = mu, shape2 = 5)
    unique(mu/(mu + 5))

    
    # check
    hist(dat$Y, xlim = c(0,1))
    hist(dat$Y[dat$Group == 'Group_1'], xlim = c(0,1))
    hist(dat$Y[dat$Group == 'Group_2'], xlim = c(0,1))
    aggregate(Y ~ 1, FUN = mean, data = dat)
    aggregate(Y ~ Group, FUN = mean, data = dat)
    aggregate(Y ~ Group, FUN = var, data = dat)
    

```
